#!/usr/bin/env python3
"""
Wire the generated city pages into the pages the site already has.

Two jobs, both idempotent and both safe to re-run after the legacy generators
have rewritten their output (which is why this runs as a post-processing step
rather than as edits inside generate_pages.py):

1. State pages (docs/<state>.html) get a directory of every city in that state
   with a Great Clips. Without it the 2,550 new pages would only be reachable from
   the sitemap, which is a weak crawl signal - now the path is
   home -> /states -> /texas -> /salons/tx/cypress.

2. Legacy metro pages (docs/cities/*.html) get their invented location counts
   replaced with real ones, and gain a directory of the suburbs in their market.
   Those pages claimed things like "150+ locations in New York City" when Great
   Clips has none in NYC at all; the counts here come from the official locator.

Injected blocks are wrapped in marker comments and replaced wholesale on re-run.

Usage:
    python scripts/inject_local_links.py
    python scripts/inject_local_links.py --check    # report, write nothing
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import markets  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs"

START = "<!-- GC-LOCAL-LINKS:START (generated by scripts/inject_local_links.py) -->"
END = "<!-- GC-LOCAL-LINKS:END -->"
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)


def esc(text) -> str:
    return html.escape(str(text or ""), quote=True)


def city_link(city: dict) -> str:
    return (
        f'<a href="/salons/{city["state"].lower()}/{city["slug"]}" '
        f'class="flex items-center justify-between gap-2 rounded-lg bg-slate-50 px-3 py-2 '
        f'hover:bg-purple-50 transition-colors">'
        f'<span class="text-sm font-medium text-slate-700">{esc(city["city"])}</span>'
        f'<span class="text-xs text-slate-500">{city["salon_count"]}</span></a>'
    )


def wrap(inner: str) -> str:
    return f"{START}\n{inner}\n        {END}"


def splice(html_text: str, block: str) -> tuple[str, bool]:
    """Replace an existing injected block, else insert before </main>."""
    if BLOCK_RE.search(html_text):
        return BLOCK_RE.sub(lambda _: block, html_text, count=1), True
    if "</main>" in html_text:
        return html_text.replace("</main>", f"{block}\n    </main>", 1), True
    return html_text, False


# ------------------------------------------------------------- state pages ---

def state_block(state_name: str, state_abbr: str, members: list[dict]) -> str:
    members = sorted(members, key=lambda c: c["city"])
    total_salons = sum(c["salon_count"] for c in members)
    links = "\n                    ".join(city_link(c) for c in members)

    inner = f"""        <section class="bg-white rounded-2xl shadow-lg p-8 mb-8">
            <h2 class="text-2xl font-bold text-slate-900 mb-2">
                Every {esc(state_name)} city with a Great Clips
            </h2>
            <p class="text-slate-600 mb-6">
                {total_salons:,} salons across {len(members):,} {esc(state_name)} cities and suburbs.
                Open a city for its full salon list - addresses, phone numbers and hours - plus the
                national, statewide and market coupons valid there. The number beside each city is
                how many salons it has.
            </p>
            <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">
                    {links}
            </div>
            <p class="mt-6 text-sm text-slate-500">
                Counts come from the official Great Clips salon locator.
                <a href="/salons" class="text-purple-600 hover:underline">Browse all states &rarr;</a>
            </p>
        </section>"""
    return wrap(inner)


# "Houston" / "100+ locations" cards in the Major Cities grid on a state page.
CITY_CARD_RE = re.compile(
    r'(<h3 class="font-semibold text-slate-900">([^<]+)</h3>\s*'
    r'<p class="text-slate-500 text-sm">)\d+\+ locations(</p>)'
)
# "...with over 500 locations across the state."
STATE_TOTAL_RE = re.compile(r"over [\d,]+ locations")
# "230+ locations", "230+ Great Clips locations in California"
STATE_ESTIMATE_RE = re.compile(r"[\d,]+\+(?=([^<>]{0,45}?locations?\b))")
# Brand-wide figures ("4,400+ US locations") are Great Clips' own published number
# for the whole chain, so they are left alone - our count is US-only.
NATIONWIDE_HINT = re.compile(r"\b(?:US|U\.S\.|United States|nationwide|nationally)\b")


def fix_state_page_counts(
    text: str,
    state_abbr: str,
    members: list[dict],
    cities: dict,
    metros: dict,
    lookup: dict,
) -> tuple[str, int]:
    """Replace invented location counts on a state page with real ones.

    The city cards name metros, so each gets its market's salon total; the prose
    total gets the state's actual salon count.
    """
    fixed = 0

    def card(match: re.Match) -> str:
        nonlocal fixed
        label = match.group(2).strip()
        resolved = markets.resolve_area(label, cities, lookup, state_abbr)
        keys = resolved.get("metro_keys") or []
        if not keys:
            return match.group(0)  # leave anything we cannot verify
        total = sum(metros[k]["salon_count"] for k in dict.fromkeys(keys) if k in metros)
        if not total:
            return match.group(0)
        fixed += 1
        plural = "location" if total == 1 else "locations"
        return f"{match.group(1)}{total} {plural}{match.group(3)}"

    text = CITY_CARD_RE.sub(card, text)

    state_total = sum(c["salon_count"] for c in members)

    text, n = STATE_TOTAL_RE.subn(f"{state_total} locations", text)
    fixed += n

    def estimate(match: re.Match) -> str:
        nonlocal fixed
        if NATIONWIDE_HINT.search(match.group(1) or ""):
            return match.group(0)
        fixed += 1
        return str(state_total)

    text = STATE_ESTIMATE_RE.sub(estimate, text)
    return text, fixed


def inject_state_pages(
    cities: dict, metros: dict, check: bool
) -> tuple[int, int, int]:
    by_state: dict[str, list[dict]] = {}
    for city in cities.values():
        by_state.setdefault(city["state"], []).append(city)

    lookup = markets.build_city_lookup(cities)
    updated = skipped = counts_fixed = 0
    for state_abbr, members in sorted(by_state.items()):
        state_name = members[0]["state_name"]
        path = DOCS / f"{state_name.lower().replace(' ', '-')}.html"
        if not path.exists():
            skipped += 1
            continue

        original = path.read_text(encoding="utf-8")
        text, fixed = fix_state_page_counts(
            original, state_abbr, members, cities, metros, lookup
        )
        if fixed:
            counts_fixed += 1
        patched, ok = splice(text, state_block(state_name, state_abbr, members))
        if not ok:
            print(f"  ! no </main> in {path.name}, skipped")
            skipped += 1
            continue
        if patched != original and not check:
            path.write_text(patched, encoding="utf-8")
        if patched != original:
            updated += 1
    return updated, skipped, counts_fixed


# ------------------------------------------------------ legacy city pages ----

# The 68 legacy pages come from two generator lineages with different wording, so
# the invented "N+" counts appear in several shapes. Patterns run in order; each
# replacement removes the "+" so a later, broader pattern cannot double-fire, and
# re-running the script is a no-op. Anything mentioning a metro takes the market
# count; anything naming the city alone takes that city's own count.
#
# Nothing here can touch price strings like "$5.99+" because every pattern
# requires the word "location" (or a stat-tile <div>) nearby.
LOCATION_PATTERNS: list[tuple[re.Pattern, str]] = [
    # "...80+ Great Clips locations in the San Antonio, Texas metropolitan area"
    (re.compile(r"\d+\+(?=[^<>]{0,70}?metropolitan area)"), "market"),
    # "approximately 42+ Great Clips locations in the Chicago metro area"
    (re.compile(r"\d+\+(?=[^<>]{0,70}?metro area)"), "market"),
    # "Save $5-$10 on haircuts at 80+ San Antonio area locations."
    (re.compile(r"\d+\+(?=[^<>]{0,40}?area locations)"), "market"),
    # "Great Clips has 80+ convenient locations throughout..."
    (re.compile(r"\d+\+(?=\s+convenient locations)"), "market"),
    # the stat tile: >80+</div>
    (re.compile(r"(?<=>)\d+\+(?=</div>)"), "city"),
    # "80+ locations in San Antonio, Texas" / "the 6 Great Clips locations in X"
    (re.compile(r"\d+\+(?=[^<>]{0,30}?locations? in\b)"), "city"),
    # anything else tied to the word "location"
    (re.compile(r"\d+\+(?=[^<>]{0,50}?[Ll]ocations?\b)"), "market"),
]


def read_city_identity(text: str) -> tuple[str, str] | None:
    """Pull "City, ST" out of a legacy page."""
    m = re.search(r"\d+\+ locations in ([A-Za-z .'-]+), ([A-Z]{2})", text)
    if m:
        return m.group(1).strip(), m.group(2)
    m = re.search(
        r'"addressLocality":\s*"([^"]+)",\s*\n?\s*"addressRegion":\s*"([A-Z]{2})"', text
    )
    if m:
        return m.group(1).strip(), m.group(2)
    return None


def resolve_market(
    city_name: str, state: str, cities: dict, metros: dict, lookup: dict
) -> tuple[dict | None, dict | None]:
    """Return (city record or None, metro record) for a legacy page's city."""
    key = f"{state}/{markets.slugify(markets.normalize_city(city_name))}"
    city = cities.get(key)
    if city:
        return city, metros[city["metro_key"]]

    # No salons in this city (New York, Miami, Boston...). Fall back to whichever
    # market surrounds it, the same way an area coupon is resolved.
    resolved = markets.resolve_area(city_name, cities, lookup, state)
    if resolved["metro_keys"]:
        return None, metros[resolved["metro_keys"][0]]
    return None, None


def city_block(
    city_name: str, city: dict | None, metro: dict, cities: dict
) -> str:
    members = sorted(
        (cities[k] for k in metro["city_keys"]), key=lambda c: (-c["salon_count"], c["city"])
    )
    links = "\n                    ".join(city_link(c) for c in members)

    if city:
        lead = (
            f"{esc(city['city'])} itself has {city['salon_count']} "
            f"Great Clips salon{'' if city['salon_count'] == 1 else 's'}. "
            f"The wider {esc(metro['name'])} coupon market covers "
            f"{metro['salon_count']} salons across {metro['city_count']} cities, and "
            f"market-wide offers are generally valid at any of them."
        )
        own = (
            f'<p class="mb-6"><a href="/salons/{city["state"].lower()}/{city["slug"]}" '
            f'class="text-purple-600 font-semibold hover:underline">'
            f'See all {city["salon_count"]} salons in {esc(city["city"])} &rarr;</a></p>'
        )
    else:
        nearest = members[0] if members else None
        lead = (
            f"Great Clips has no salons in {esc(city_name)} itself - the brand operates "
            f"in suburban and strip-mall locations rather than dense city centres. The "
            f"nearest salons are in the surrounding {esc(metro['name'])} market, which "
            f"covers {metro['salon_count']} salons across {metro['city_count']} cities."
        )
        own = (
            f'<p class="mb-6"><a href="/salons/{nearest["state"].lower()}/{nearest["slug"]}" '
            f'class="text-purple-600 font-semibold hover:underline">'
            f'Nearest salons: {esc(nearest["city"])}, {esc(nearest["state"])} &rarr;</a></p>'
            if nearest
            else ""
        )

    inner = f"""        <section class="bg-white rounded-2xl shadow-sm p-8 mb-10">
            <h2 class="text-2xl font-bold text-slate-900 mb-3">
                Where {esc(metro['name'])} coupons are valid
            </h2>
            <p class="text-slate-600 mb-4">{lead}</p>
            {own}
            <h3 class="font-semibold text-slate-900 mb-3">
                All {metro['city_count']} cities in the {esc(metro['name'])} market
            </h3>
            <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">
                    {links}
            </div>
            <p class="mt-6 text-sm text-slate-500">
                Salon counts come from the official Great Clips salon locator.
                Participation in any given offer is set by each franchise owner.
            </p>
        </section>"""
    return wrap(inner)


def inject_city_pages(cities: dict, metros: dict, check: bool) -> tuple[int, int, int]:
    lookup = markets.build_city_lookup(cities)
    city_dir = DOCS / "cities"
    if not city_dir.exists():
        return 0, 0, 0

    updated = skipped = fixed_counts = 0
    for path in sorted(city_dir.glob("*.html")):
        original = path.read_text(encoding="utf-8")
        identity = read_city_identity(original)
        if not identity:
            print(f"  ! could not identify city for {path.name}, skipped")
            skipped += 1
            continue

        city_name, state = identity
        city, metro = resolve_market(city_name, state, cities, metros, lookup)
        if metro is None:
            print(f"  ! no market found for {city_name}, {state}, skipped")
            skipped += 1
            continue

        text = original
        counts = {
            "market": str(metro["salon_count"]),
            # A city with no salons of its own (New York, Miami) has nothing
            # honest to show as a city count, so it falls back to the market.
            "city": str(city["salon_count"]) if city else str(metro["salon_count"]),
        }
        before = text
        for pattern, which in LOCATION_PATTERNS:
            text = pattern.sub(counts[which], text)

        if city is None:
            # Great Clips has nothing in this city, so a bare number would make the
            # page claim "15 locations in New York City" - false, and contradicted
            # by the block we inject below. Say "near" instead. "locations in THE
            # <city> metropolitan area" is left alone: that one is true.
            text = re.sub(
                r"locations in (?!the\b)" + re.escape(city_name),
                f"locations near {city_name}",
                text,
            )
            text = re.sub(
                r"locations across the " + re.escape(metro["name"]) + r" area",
                f"locations near {city_name}",
                text,
            )

        if text != before:
            fixed_counts += 1

        text, ok = splice(text, city_block(city_name, city, metro, cities))
        if not ok:
            print(f"  ! no </main> in {path.name}, links not added")

        if text != original:
            if not check:
                path.write_text(text, encoding="utf-8")
            updated += 1

    return updated, skipped, fixed_counts


MONTH_NAMES = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

# Pages that carry a month in their title but are not month-specific content.
# Month landing pages (january-2026.html and friends) are deliberately excluded -
# naming their own month is the entire point of them.
EVERGREEN_WITH_MONTH = [
    "states.html", "5-99-coupon.html", "6-99-coupon.html",
    "printable-coupons.html", "coupon-codes.html", "senior-discount.html",
    "prices.html", "how-to-use.html", "faq.html",
]

MONTH_TOKEN_RE = re.compile(
    r"\b(" + "|".join(MONTH_NAMES) + r")\s+(20\d\d)\b"
)


def refresh_stale_months(cities: dict, check: bool) -> tuple[int, int]:
    """Roll a stale month in a page's title and meta tags forward to the current one.

    generate_pages.py holds only 19 states, so the other 31 state pages are produced
    by nothing and had been frozen since June - 33 pages were advertising "June
    2026" in late August, which reads as abandoned in a search result. Rather than
    strip the month (it is useful for coupon queries) this rewrites it, and it runs
    on every scrape so it cannot drift again.

    Only <title>, the meta description and og equivalents are touched: body copy may
    discuss a month for a reason.
    """
    now = datetime.now()
    current = f"{MONTH_NAMES[now.month - 1]} {now.year}"

    targets = [DOCS / f"{c['state_name'].lower().replace(' ', '-')}.html"
               for c in cities.values()]
    targets += [DOCS / name for name in EVERGREEN_WITH_MONTH]

    scanned = updated = 0
    seen = set()
    for path in targets:
        if path in seen or not path.exists():
            continue
        seen.add(path)
        scanned += 1
        original = path.read_text(encoding="utf-8", errors="replace")

        def fix_region(match: re.Match) -> str:
            return MONTH_TOKEN_RE.sub(current, match.group(0))

        text = original
        for pattern in (
            r"<title>.*?</title>",
            r'<meta name="description" content="[^"]*"',
            r'<meta property="og:title" content="[^"]*"',
            r'<meta property="og:description" content="[^"]*"',
        ):
            text = re.sub(pattern, fix_region, text, flags=re.S)

        if text != original:
            updated += 1
            if not check:
                path.write_text(text, encoding="utf-8")
    return scanned, updated


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="report without writing")
    args = ap.parse_args()

    cities, metros = markets.build_all()

    print("State pages:")
    updated, skipped, counts = inject_state_pages(cities, metros, args.check)
    print(f"  updated {updated}, skipped {skipped}, location counts corrected on {counts}")

    scanned, refreshed = refresh_stale_months(cities, args.check)
    print(f"Stale months: {refreshed} of {scanned} pages rolled to the current month")

    print("Legacy city pages:")
    updated_c, skipped_c, fixed = inject_city_pages(cities, metros, args.check)
    print(f"  updated {updated_c}, skipped {skipped_c}, location counts corrected on {fixed}")

    if args.check:
        print("\n(--check: no files were written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
