#!/usr/bin/env python3
"""
Wire the generated city pages into the pages the site already has.

Two jobs, both idempotent and both safe to re-run after the legacy generators
have rewritten their output (which is why this runs as a post-processing step
rather than as edits inside generate_pages.py):

1. State pages (docs/<state>.html) get a directory of every city in that state
   with a Great Clips. Without it the 2,550 new pages would only be reachable from
   the sitemap, which is a weak crawl signal - now the path is
   home -> /states -> /texas -> /salons/tx/cypress.

2. Legacy metro pages (docs/cities/*.html) get their invented location counts
   replaced with real ones, and gain a directory of the suburbs in their market.
   Those pages claimed things like "150+ locations in New York City" when Great
   Clips has none in NYC at all; the counts here come from the official locator.

Injected blocks are wrapped in marker comments and replaced wholesale on re-run.

Usage:
    python scripts/inject_local_links.py
    python scripts/inject_local_links.py --check    # report, write nothing
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import markets  # noqa: E402
import national_offer  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs"

START = "<!-- GC-LOCAL-LINKS:START (generated by scripts/inject_local_links.py) -->"
END = "<!-- GC-LOCAL-LINKS:END -->"
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)

NAT_START = "<!-- GC-NATIONAL-OFFER:START (generated by scripts/inject_local_links.py) -->"
NAT_END = "<!-- GC-NATIONAL-OFFER:END -->"
NAT_BLOCK_RE = re.compile(re.escape(NAT_START) + r".*?" + re.escape(NAT_END), re.S)

MAIN_OPEN_RE = re.compile(r"<main\b[^>]*>")


def esc(text) -> str:
    return html.escape(str(text or ""), quote=True)


def city_link(city: dict) -> str:
    return (
        f'<a href="/salons/{city["state"].lower()}/{city["slug"]}" '
        f'class="flex items-center justify-between gap-2 rounded-lg bg-slate-50 px-3 py-2 '
        f'hover:bg-purple-50 transition-colors">'
        f'<span class="text-sm font-medium text-slate-700">{esc(city["city"])}</span>'
        f'<span class="text-xs text-slate-500">{city["salon_count"]}</span></a>'
    )


def wrap(inner: str) -> str:
    return f"{START}\n{inner}\n        {END}"


def splice(html_text: str, block: str) -> tuple[str, bool]:
    """Replace an existing injected block, else insert before </main>."""
    if BLOCK_RE.search(html_text):
        return BLOCK_RE.sub(lambda _: block, html_text, count=1), True
    if "</main>" in html_text:
        return html_text.replace("</main>", f"{block}\n    </main>", 1), True
    return html_text, False


# --------------------------------------------------------- nationwide offer ---
#
# The salon pages under /salons have carried the live nationwide coupon in their
# static HTML since they were built, but the state and metro pages never did:
# they are older, three different generators own them, and 31 of the 50 state
# pages are owned by no generator at all. So a $5.00 coupon valid in every state
# was invisible on /alabama while that page's own schema advertised $6.99.
#
# Injecting here rather than in the templates covers all 118 pages in one pass,
# whatever produced them, and re-runs on every scrape so the price cannot drift.


def national_block(
    offer: dict,
    place: str,
    canonical: str,
    salon_count: int,
    reach: str,
) -> str:
    """Visible nationwide-offer section plus its schema.org Offer.

    `reach` completes "... including all N salons in <reach>", so it names the
    thing the count actually covers - a state, or a metro market.
    """
    price = national_offer.price_text(offer)
    plural = "salon" if salon_count == 1 else "salons"
    schema_price = national_offer.schema_price(offer)

    offer_node = {
        "@context": "https://schema.org",
        "@type": "Offer",
        "name": f"Great Clips {price} haircut coupon (nationwide)",
        "description": (
            f"Nationwide Great Clips coupon for a {price} haircut, valid at "
            f"participating Great Clips salons across the United States, "
            f"including {salon_count} in {reach}."
        ),
        "price": schema_price,
        "priceCurrency": "USD",
        "availability": "https://schema.org/InStock",
        "url": canonical,
        "areaServed": {"@type": "Country", "name": "United States"},
        "itemOffered": {
            "@type": "Service",
            "name": "Haircut",
            "provider": {"@type": "Organization", "name": "Great Clips"},
        },
    }
    if offer.get("expiration"):
        offer_node["validThrough"] = offer["expiration"]

    inner = f"""        <section class="bg-emerald-50 border border-emerald-200 rounded-2xl p-8 mb-10">
            <div class="flex items-start gap-4">
                <span class="text-3xl leading-none">&#127758;</span>
                <div>
                    <h2 class="text-2xl font-bold text-slate-900 mb-3">
                        Nationwide Great Clips coupon &ndash; valid in {esc(place)}
                    </h2>
                    <p class="text-slate-700 mb-4">
                        A <strong>{esc(price)} Great Clips haircut coupon</strong> is currently running
                        nationwide, valid at participating Great Clips salons anywhere in the United
                        States &ndash; including all {salon_count} {plural} in {esc(reach)}. Unlike the
                        market-specific offers below, this one does not depend on where you are.
                    </p>
                    <a href="/" class="inline-block bg-gradient-to-r from-emerald-600 to-teal-600
                              hover:from-emerald-700 hover:to-teal-700 text-white font-semibold
                              py-2.5 px-5 rounded-xl transition-all shadow-md">
                        Get the {esc(price)} nationwide coupon
                    </a>
                    <p class="text-xs text-slate-500 mt-3">
                        Participation is set by each franchise owner, so confirm at the salon.
                    </p>
                    <h3 class="font-semibold text-slate-900 mt-6 mb-2">
                        {esc(faq_question(place))}
                    </h3>
                    <p class="text-slate-700">{esc(faq_answer(offer, salon_count, reach))}</p>
                </div>
            </div>
        </section>
        <script type="application/ld+json">
{json.dumps(offer_node, indent=8)}
        </script>"""
    return f"{NAT_START}\n{inner}\n        {NAT_END}"


def splice_national(html_text: str, block: str | None) -> tuple[str, bool]:
    """Replace the nationwide block, insert it at the top of <main>, or drop it.

    A None block removes any block already present, so that when Great Clips
    ends the nationwide coupon the pages stop advertising it on the next run
    instead of keeping a dead price forever.
    """
    if NAT_BLOCK_RE.search(html_text):
        if block is None:
            return NAT_BLOCK_RE.sub("", html_text, count=1), True
        return NAT_BLOCK_RE.sub(lambda _: block, html_text, count=1), True
    if block is None:
        return html_text, True
    match = MAIN_OPEN_RE.search(html_text)
    if not match:
        return html_text, False
    at = match.end()
    return f"{html_text[:at]}\n{block}{html_text[at:]}", True


# Fabricated price claims baked into the page templates. Every pattern matches
# any price rather than the specific stale literal, so a run both corrects the
# old hardcoded figure and tracks the feed if the real floor price later moves.
#
# "$15-19" / "$15-$21" regular prices are deliberately not matched: those are
# Great Clips' undiscounted menu prices, not coupon prices.
STALE_PRICE_PATTERNS: list[tuple[re.Pattern, str]] = [
    # meta description: "Get $5.99, $6.99, $7.99 haircut deals at ..." - the whole
    # invented list collapses to the one price that is really running.
    (re.compile(r"Get \$\d+\.\d\d(?:,? (?:and )?\$\d+\.\d\d)* haircut deals"),
     "Get {price} haircut deals"),
    # "as little as $5.99-$8.99" / "as little as $5.99"
    (re.compile(r"as little as \$\d+\.\d\d(?:\s*-\s*\$\d+\.\d\d)?"),
     "as little as {price}"),
    # "deals from $5.99-$8.99" / "Updated daily with $5.99-$8.99 deals"
    (re.compile(r"from \$\d+\.\d\d\s*-\s*\$\d+\.\d\d"), "from {price}"),
    (re.compile(r"with \$\d+\.\d\d\s*-\s*\$\d+\.\d\d deals"), "with {price} deals"),
    # "Prices typically range from $5.99 to $8.99 with a coupon"
    (re.compile(r"range from <strong>\$\d+\.\d\d to \$\d+\.\d\d</strong>"),
     "start at <strong>{price}</strong>"),
    # The single-price shapes generate_pages.py emits now that it reads the feed.
    # They still need matching here: the templates only run in the state-pages
    # workflow, while this script runs on every scrape, so between page rebuilds
    # this is the only thing keeping the quoted price current.
    (re.compile(r"deals from \$\d+\.\d\d at\b"), "deals from {price} at"),
    (re.compile(r"Updated daily, from \$\d+\.\d\d\."), "Updated daily, from {price}."),
    (re.compile(r"start at <strong>\$\d+\.\d\d</strong>"),
     "start at <strong>{price}</strong>"),
    # og:title: "Great Clips Coupons Alabama - $5.99 Haircuts September 2026"
    (re.compile(r"- \$\d+\.\d\d\+? Haircuts"), "- {price} Haircuts"),
    # <title> and og:title on the metro pages: "... - $5.99 Haircut Deals (2026)"
    (re.compile(r"- \$\d+\.\d\d\+? Haircut Deals"), "- {price} Haircut Deals"),
    # "Most coupons offer prices between $5.99 and $8.99 - well below the regular
    # price of $15-$19." The range was invented; only the live floor is defensible.
    (re.compile(r"Most coupons offer prices between \$\d+\.\d\d and \$\d+\.\d\d"),
     "The cheapest coupon running right now is {price}"),
    # ...and the rewritten form, so later runs keep the figure current.
    (re.compile(r"The cheapest coupon running right now is \$\d+\.\d\d"),
     "The cheapest coupon running right now is {price}"),
    # the green stat tile on state pages
    (re.compile(r'(<div class="text-2xl font-bold text-green-600">)\$\d+\.\d\d(</div>)'),
     r"\g<1>{price}\g<2>"),
    # The metro pages' "Lowest Price" tile. Anchored on its label so it cannot hit
    # the state pages' "Lowest AZ price we've tracked" tile, which shows a real
    # figure from data/state_history_stats.json rather than an invented one.
    (re.compile(r'(<div class="text-4xl font-bold text-purple-600 mb-2">)\$\d+\.\d\d'
                r'(</div>\s*<div class="text-slate-600">Lowest Price</div>)'),
     r"\g<1>{price}\g<2>"),
    # "Get $5.99 haircuts at Alabama Great Clips" / "... haircuts in Houston, Dallas"
    (re.compile(r"Get \$\d+\.\d\d haircuts (at|in)\b"), r"Get {price} haircuts \g<1>"),
    # A tile labelled as the current lowest coupon price, so it has to be the feed's.
    # "Lowest <ST> price we've tracked" and "median coupon price in <ST>" tiles are
    # left alone: those are real figures from data/state_history_stats.json.
    (re.compile(r'(<div class="text-3xl font-bold text-green-600">)\$\d+\.\d\d'
                r'(</div>\s*<p class="text-slate-600">Lowest Coupon Price</p>)'),
     r"\g<1>{price}\g<2>"),
    # "you can get haircuts for as low as $5.99 at ..."
    (re.compile(r"as low as \$\d+\.\d\d"), "as low as {price}"),
    # client-side render fallback: ${coupon.price || '$6.99'}
    (re.compile(r"(\|\|\s*)'\$\d+\.\d\d'"), r"\g<1>'{price}'"),
    # the stale ItemList > Offer that 30 state pages ship
    (re.compile(r'"name": "\$\d+\.\d\d Haircut Coupon - '), '"name": "{price} Haircut Coupon - '),
    (re.compile(r'("@type": "Offer",\s*\n\s*"position": 1,(?:.|\n)*?"price": ")\d+\.\d\d(")'),
     r"\g<1>{schema}\g<2>"),
]


def fix_stale_prices(text: str, price: str) -> tuple[str, int]:
    """Point every quoted coupon price at the cheapest one actually in the feed."""
    schema = price.replace("$", "")
    fixed = 0
    for pattern, replacement in STALE_PRICE_PATTERNS:
        repl = replacement.replace("{price}", price).replace("{schema}", schema)
        text, n = pattern.subn(repl, text)
        fixed += n
    return text, fixed


# The nationwide question is the one answer that holds identically on every page,
# so it goes first - same ordering as the salon pages in generate_local_pages.py.
FAQ_MARK = "gc-national-faq"
FAQPAGE_RE = re.compile(
    r'<script type="application/ld\+json">\s*(\{[^<]*?"@type":\s*"FAQPage".*?\})\s*</script>',
    re.S,
)


def faq_question(place: str) -> str:
    return f"Is there a nationwide Great Clips coupon that works in {place}?"


def faq_answer(offer: dict, salon_count: int, reach: str) -> str:
    """Answer text, rendered visibly and reused verbatim in the FAQPage schema.

    Keeping one source for both is what makes the schema legitimate: structured
    data has to match what a reader actually sees on the page.
    """
    price = national_offer.price_text(offer)
    plural = "salon" if salon_count == 1 else "salons"
    return (
        f"Yes. A {price} Great Clips haircut coupon is currently running nationwide "
        f"and is valid at participating Great Clips salons anywhere in the United "
        f"States, including the {salon_count} {plural} in {reach}. It is not tied to "
        f"a city or market, so it applies here regardless of which local offers are "
        f"running."
    )


def national_faq(offer: dict, place: str, salon_count: int, reach: str) -> dict:
    return {
        "@type": "Question",
        "name": faq_question(place),
        "acceptedAnswer": {
            "@type": "Answer",
            "text": faq_answer(offer, salon_count, reach),
            "identifier": FAQ_MARK,
        },
    }


def add_national_faq(
    text: str, offer: dict | None, place: str, salon_count: int, reach: str
) -> tuple[str, bool]:
    """Put the nationwide Q&A at the head of the page's FAQPage schema.

    Rewritten in place on every run and keyed by an identifier rather than
    appended blindly, so re-runs replace it instead of stacking duplicates and a
    price change propagates. Dropped entirely when no nationwide coupon is live.

    30 of the 50 state pages and 50 of the 68 metro pages carry no FAQPage at all,
    so one is created for them holding just this question - which the injected
    section states visibly, immediately above.
    """
    match = FAQPAGE_RE.search(text)

    if not match:
        if not offer:
            return text, False
        node = {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [national_faq(offer, place, salon_count, reach)],
        }
        block = (
            '        <script type="application/ld+json">\n'
            + json.dumps(node, indent=8)
            + "\n        </script>\n"
        )
        end = text.find(NAT_END)
        if end == -1:
            return text, False
        return text[:end] + block + text[end:], True

    try:
        node = json.loads(match.group(1))
    except json.JSONDecodeError:
        return text, False

    entries = node.get("mainEntity")
    if not isinstance(entries, list):
        return text, False

    kept = [
        q for q in entries
        if not (isinstance(q, dict)
                and (q.get("acceptedAnswer") or {}).get("identifier") == FAQ_MARK)
    ]
    node["mainEntity"] = (
        [national_faq(offer, place, salon_count, reach)] + kept if offer else kept
    )
    if node["mainEntity"] == entries:
        return text, False

    block = (
        '<script type="application/ld+json">\n'
        + json.dumps(node, indent=8)
        + "\n    </script>"
    )
    return text[: match.start()] + block + text[match.end() :], True


# ------------------------------------------------------------- state pages ---

def state_block(state_name: str, state_abbr: str, members: list[dict]) -> str:
    members = sorted(members, key=lambda c: c["city"])
    total_salons = sum(c["salon_count"] for c in members)
    links = "\n                    ".join(city_link(c) for c in members)

    inner = f"""        <section class="bg-white rounded-2xl shadow-lg p-8 mb-8">
            <h2 class="text-2xl font-bold text-slate-900 mb-2">
                Every {esc(state_name)} city with a Great Clips
            </h2>
            <p class="text-slate-600 mb-6">
                {total_salons:,} salons across {len(members):,} {esc(state_name)} cities and suburbs.
                Open a city for its full salon list - addresses, phone numbers and hours - plus the
                national, statewide and market coupons valid there. The number beside each city is
                how many salons it has.
            </p>
            <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">
                    {links}
            </div>
            <p class="mt-6 text-sm text-slate-500">
                Counts come from the official Great Clips salon locator.
                <a href="/salons" class="text-purple-600 hover:underline">Browse all states &rarr;</a>
            </p>
        </section>"""
    return wrap(inner)


# "Houston" / "100+ locations" cards in the Major Cities grid on a state page.
CITY_CARD_RE = re.compile(
    r'(<h3 class="font-semibold text-slate-900">([^<]+)</h3>\s*'
    r'<p class="text-slate-500 text-sm">)\d+\+ locations(</p>)'
)
# "...with over 500 locations across the state."
STATE_TOTAL_RE = re.compile(r"over [\d,]+ locations")
# "230+ locations", "230+ Great Clips locations in California"
STATE_ESTIMATE_RE = re.compile(r"[\d,]+\+(?=([^<>]{0,45}?locations?\b))")
# Brand-wide figures ("4,400+ US locations") are Great Clips' own published number
# for the whole chain, so they are left alone - our count is US-only.
NATIONWIDE_HINT = re.compile(r"\b(?:US|U\.S\.|United States|nationwide|nationally)\b")


def fix_state_page_counts(
    text: str,
    state_abbr: str,
    members: list[dict],
    cities: dict,
    metros: dict,
    lookup: dict,
) -> tuple[str, int]:
    """Replace invented location counts on a state page with real ones.

    The city cards name metros, so each gets its market's salon total; the prose
    total gets the state's actual salon count.
    """
    fixed = 0

    def card(match: re.Match) -> str:
        nonlocal fixed
        label = match.group(2).strip()
        resolved = markets.resolve_area(label, cities, lookup, state_abbr)
        keys = resolved.get("metro_keys") or []
        if not keys:
            return match.group(0)  # leave anything we cannot verify
        total = sum(metros[k]["salon_count"] for k in dict.fromkeys(keys) if k in metros)
        if not total:
            return match.group(0)
        fixed += 1
        plural = "location" if total == 1 else "locations"
        return f"{match.group(1)}{total} {plural}{match.group(3)}"

    text = CITY_CARD_RE.sub(card, text)

    state_total = sum(c["salon_count"] for c in members)

    text, n = STATE_TOTAL_RE.subn(f"{state_total} locations", text)
    fixed += n

    def estimate(match: re.Match) -> str:
        nonlocal fixed
        if NATIONWIDE_HINT.search(match.group(1) or ""):
            return match.group(0)
        fixed += 1
        return str(state_total)

    text = STATE_ESTIMATE_RE.sub(estimate, text)
    return text, fixed


def inject_state_pages(
    cities: dict, metros: dict, check: bool, offer: dict | None, quote: str
) -> tuple[int, int, int, int]:
    by_state: dict[str, list[dict]] = {}
    for city in cities.values():
        by_state.setdefault(city["state"], []).append(city)

    lookup = markets.build_city_lookup(cities)
    price = quote
    updated = skipped = counts_fixed = priced = 0
    for state_abbr, members in sorted(by_state.items()):
        state_name = members[0]["state_name"]
        slug = state_name.lower().replace(" ", "-")
        path = DOCS / f"{slug}.html"
        if not path.exists():
            skipped += 1
            continue

        original = path.read_text(encoding="utf-8")
        text, fixed = fix_state_page_counts(
            original, state_abbr, members, cities, metros, lookup
        )
        if fixed:
            counts_fixed += 1

        if price:
            text, n = fix_stale_prices(text, price)
            if n:
                priced += 1

        state_salons = sum(c["salon_count"] for c in members)
        block = (
            national_block(
                offer,
                state_name,
                f"https://greatclipsdeal.com/{slug}",
                state_salons,
                state_name,
            )
            if offer
            else None
        )
        text, nat_ok = splice_national(text, block)
        if not nat_ok:
            print(f"  ! no <main> in {path.name}, nationwide offer not added")
        text, _ = add_national_faq(text, offer, state_name, state_salons, state_name)

        patched, ok = splice(text, state_block(state_name, state_abbr, members))
        if not ok:
            print(f"  ! no </main> in {path.name}, skipped")
            skipped += 1
            continue
        if patched != original and not check:
            path.write_text(patched, encoding="utf-8")
        if patched != original:
            updated += 1
    return updated, skipped, counts_fixed, priced


# ------------------------------------------------------ legacy city pages ----

# The 68 legacy pages come from two generator lineages with different wording, so
# the invented "N+" counts appear in several shapes. Patterns run in order; each
# replacement removes the "+" so a later, broader pattern cannot double-fire, and
# re-running the script is a no-op. Anything mentioning a metro takes the market
# count; anything naming the city alone takes that city's own count.
#
# Nothing here can touch price strings like "$5.99+" because every pattern
# requires the word "location" (or a stat-tile <div>) nearby.
LOCATION_PATTERNS: list[tuple[re.Pattern, str]] = [
    # "...80+ Great Clips locations in the San Antonio, Texas metropolitan area"
    (re.compile(r"\d+\+(?=[^<>]{0,70}?metropolitan area)"), "market"),
    # "approximately 42+ Great Clips locations in the Chicago metro area"
    (re.compile(r"\d+\+(?=[^<>]{0,70}?metro area)"), "market"),
    # "Save $5-$10 on haircuts at 80+ San Antonio area locations."
    (re.compile(r"\d+\+(?=[^<>]{0,40}?area locations)"), "market"),
    # "Great Clips has 80+ convenient locations throughout..."
    (re.compile(r"\d+\+(?=\s+convenient locations)"), "market"),
    # the stat tile: >80+</div>
    (re.compile(r"(?<=>)\d+\+(?=</div>)"), "city"),
    # "80+ locations in San Antonio, Texas" / "the 6 Great Clips locations in X"
    (re.compile(r"\d+\+(?=[^<>]{0,30}?locations? in\b)"), "city"),
    # anything else tied to the word "location"
    (re.compile(r"\d+\+(?=[^<>]{0,50}?[Ll]ocations?\b)"), "market"),
]


def read_city_identity(text: str) -> tuple[str, str] | None:
    """Pull "City, ST" out of a legacy page."""
    m = re.search(r"\d+\+ locations in ([A-Za-z .'-]+), ([A-Z]{2})", text)
    if m:
        return m.group(1).strip(), m.group(2)
    m = re.search(
        r'"addressLocality":\s*"([^"]+)",\s*\n?\s*"addressRegion":\s*"([A-Z]{2})"', text
    )
    if m:
        return m.group(1).strip(), m.group(2)
    return None


def resolve_market(
    city_name: str, state: str, cities: dict, metros: dict, lookup: dict
) -> tuple[dict | None, dict | None]:
    """Return (city record or None, metro record) for a legacy page's city."""
    key = f"{state}/{markets.slugify(markets.normalize_city(city_name))}"
    city = cities.get(key)
    if city:
        return city, metros[city["metro_key"]]

    # No salons in this city (New York, Miami, Boston...). Fall back to whichever
    # market surrounds it, the same way an area coupon is resolved.
    resolved = markets.resolve_area(city_name, cities, lookup, state)
    if resolved["metro_keys"]:
        return None, metros[resolved["metro_keys"][0]]
    return None, None


def city_block(
    city_name: str, city: dict | None, metro: dict, cities: dict
) -> str:
    members = sorted(
        (cities[k] for k in metro["city_keys"]), key=lambda c: (-c["salon_count"], c["city"])
    )
    links = "\n                    ".join(city_link(c) for c in members)

    if city:
        lead = (
            f"{esc(city['city'])} itself has {city['salon_count']} "
            f"Great Clips salon{'' if city['salon_count'] == 1 else 's'}. "
            f"The wider {esc(metro['name'])} coupon market covers "
            f"{metro['salon_count']} salons across {metro['city_count']} cities, and "
            f"market-wide offers are generally valid at any of them."
        )
        own = (
            f'<p class="mb-6"><a href="/salons/{city["state"].lower()}/{city["slug"]}" '
            f'class="text-purple-600 font-semibold hover:underline">'
            f'See all {city["salon_count"]} salons in {esc(city["city"])} &rarr;</a></p>'
        )
    else:
        nearest = members[0] if members else None
        lead = (
            f"Great Clips has no salons in {esc(city_name)} itself - the brand operates "
            f"in suburban and strip-mall locations rather than dense city centres. The "
            f"nearest salons are in the surrounding {esc(metro['name'])} market, which "
            f"covers {metro['salon_count']} salons across {metro['city_count']} cities."
        )
        own = (
            f'<p class="mb-6"><a href="/salons/{nearest["state"].lower()}/{nearest["slug"]}" '
            f'class="text-purple-600 font-semibold hover:underline">'
            f'Nearest salons: {esc(nearest["city"])}, {esc(nearest["state"])} &rarr;</a></p>'
            if nearest
            else ""
        )

    inner = f"""        <section class="bg-white rounded-2xl shadow-sm p-8 mb-10">
            <h2 class="text-2xl font-bold text-slate-900 mb-3">
                Where {esc(metro['name'])} coupons are valid
            </h2>
            <p class="text-slate-600 mb-4">{lead}</p>
            {own}
            <h3 class="font-semibold text-slate-900 mb-3">
                All {metro['city_count']} cities in the {esc(metro['name'])} market
            </h3>
            <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">
                    {links}
            </div>
            <p class="mt-6 text-sm text-slate-500">
                Salon counts come from the official Great Clips salon locator.
                Participation in any given offer is set by each franchise owner.
            </p>
        </section>"""
    return wrap(inner)


def inject_city_pages(
    cities: dict, metros: dict, check: bool, offer: dict | None, quote: str
) -> tuple[int, int, int, int]:
    lookup = markets.build_city_lookup(cities)
    city_dir = DOCS / "cities"
    if not city_dir.exists():
        return 0, 0, 0, 0

    price = quote
    updated = skipped = fixed_counts = priced = 0
    for path in sorted(city_dir.glob("*.html")):
        original = path.read_text(encoding="utf-8")
        identity = read_city_identity(original)
        if not identity:
            print(f"  ! could not identify city for {path.name}, skipped")
            skipped += 1
            continue

        city_name, state = identity
        city, metro = resolve_market(city_name, state, cities, metros, lookup)
        if metro is None:
            print(f"  ! no market found for {city_name}, {state}, skipped")
            skipped += 1
            continue

        text = original
        counts = {
            "market": str(metro["salon_count"]),
            # A city with no salons of its own (New York, Miami) has nothing
            # honest to show as a city count, so it falls back to the market.
            "city": str(city["salon_count"]) if city else str(metro["salon_count"]),
        }
        before = text
        for pattern, which in LOCATION_PATTERNS:
            text = pattern.sub(counts[which], text)

        if city is None:
            # Great Clips has nothing in this city, so a bare number would make the
            # page claim "15 locations in New York City" - false, and contradicted
            # by the block we inject below. Say "near" instead. "locations in THE
            # <city> metropolitan area" is left alone: that one is true.
            text = re.sub(
                r"locations in (?!the\b)" + re.escape(city_name),
                f"locations near {city_name}",
                text,
            )
            text = re.sub(
                r"locations across the " + re.escape(metro["name"]) + r" area",
                f"locations near {city_name}",
                text,
            )

        if text != before:
            fixed_counts += 1

        if price:
            text, n = fix_stale_prices(text, price)
            if n:
                priced += 1

        # A metro page's honest count is its market's: Great Clips has no salons
        # in New York City itself, so "all N salons in New York City" would be a
        # claim the rest of the page contradicts.
        block = (
            national_block(
                offer,
                city_name,
                f"https://greatclipsdeal.com/cities/{path.stem}",
                metro["salon_count"],
                f"the {metro['name']} market",
            )
            if offer
            else None
        )
        text, nat_ok = splice_national(text, block)
        if not nat_ok:
            print(f"  ! no <main> in {path.name}, nationwide offer not added")
        text, _ = add_national_faq(
            text, offer, city_name, metro["salon_count"], f"the {metro['name']} market"
        )

        text, ok = splice(text, city_block(city_name, city, metro, cities))
        if not ok:
            print(f"  ! no </main> in {path.name}, links not added")

        if text != original:
            if not check:
                path.write_text(text, encoding="utf-8")
            updated += 1

    return updated, skipped, fixed_counts, priced


MONTH_NAMES = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

# Pages that carry a month in their title but are not month-specific content.
# Month landing pages (january-2026.html and friends) are deliberately excluded -
# naming their own month is the entire point of them.
EVERGREEN_WITH_MONTH = [
    "states.html", "5-99-coupon.html", "6-99-coupon.html",
    "printable-coupons.html", "coupon-codes.html", "senior-discount.html",
    "prices.html", "how-to-use.html", "faq.html",
]

MONTH_TOKEN_RE = re.compile(
    r"\b(" + "|".join(MONTH_NAMES) + r")\s+(20\d\d)\b"
)


def refresh_stale_months(cities: dict, check: bool) -> tuple[int, int]:
    """Roll a stale month in a page's title and meta tags forward to the current one.

    generate_pages.py holds only 19 states, so the other 31 state pages are produced
    by nothing and had been frozen since June - 33 pages were advertising "June
    2026" in late August, which reads as abandoned in a search result. Rather than
    strip the month (it is useful for coupon queries) this rewrites it, and it runs
    on every scrape so it cannot drift again.

    Only <title>, the meta description and og equivalents are touched: body copy may
    discuss a month for a reason.
    """
    now = datetime.now()
    current = f"{MONTH_NAMES[now.month - 1]} {now.year}"

    targets = [DOCS / f"{c['state_name'].lower().replace(' ', '-')}.html"
               for c in cities.values()]
    targets += [DOCS / name for name in EVERGREEN_WITH_MONTH]

    scanned = updated = 0
    seen = set()
    for path in targets:
        if path in seen or not path.exists():
            continue
        seen.add(path)
        scanned += 1
        original = path.read_text(encoding="utf-8", errors="replace")

        def fix_region(match: re.Match) -> str:
            return MONTH_TOKEN_RE.sub(current, match.group(0))

        text = original
        for pattern in (
            r"<title>.*?</title>",
            r'<meta name="description" content="[^"]*"',
            r'<meta property="og:title" content="[^"]*"',
            r'<meta property="og:description" content="[^"]*"',
        ):
            text = re.sub(pattern, fix_region, text, flags=re.S)

        if text != original:
            updated += 1
            if not check:
                path.write_text(text, encoding="utf-8")
    return scanned, updated


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="report without writing")
    args = ap.parse_args()

    cities, metros = markets.build_all()

    offer = national_offer.national_offer()
    floor = national_offer.floor_price()
    if offer:
        print(f"Nationwide offer in feed: {national_offer.price_text(offer)} "
              f"- baking into state and metro pages")
    else:
        print("No nationwide offer in the feed; removing the section from pages")
    # The figure the pages quote as "as little as X". The nationwide price when one
    # is running, since that is the only price valid everywhere; otherwise the
    # feed's cheapest, so that when Great Clips ends a nationwide coupon the pages
    # fall back to a live local price instead of freezing on a dead one.
    quote = national_offer.price_text(offer) or floor or ""
    if not offer and quote:
        print(f"  quoting {quote} as the floor price (cheapest coupon in the feed)")

    print("State pages:")
    updated, skipped, counts, priced = inject_state_pages(
        cities, metros, args.check, offer, quote
    )
    print(f"  updated {updated}, skipped {skipped}, location counts corrected on {counts}, "
          f"stale prices corrected on {priced}")

    scanned, refreshed = refresh_stale_months(cities, args.check)
    print(f"Stale months: {refreshed} of {scanned} pages rolled to the current month")

    print("Legacy city pages:")
    updated_c, skipped_c, fixed, priced_c = inject_city_pages(
        cities, metros, args.check, offer, quote
    )
    print(f"  updated {updated_c}, skipped {skipped_c}, location counts corrected on {fixed}, "
          f"stale prices corrected on {priced_c}")

    if args.check:
        print("\n(--check: no files were written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
